@startuml
'https://plantuml.com/class-diagram

Client --> ProxyFactory
Client --> TeacherDao

Interface ITeacherDao{
    + void teach();
}
ITeacherDao <|-- TeacherDao

class TeacherDao{
    + void teach()
}

class ProxyFactory{
    + ProxyFactory()
    + Object getProxyInstance()
}

@enduml