@startuml
'https://plantuml.com/class-diagram

abstract class PizzaStore{
    # createPizza(String type):Pizza
    + orderPizza(String type):Pizza
}
PizzaStore <|-- DongJingPizzaStore
PizzaStore <|-- NanJingPizzaStore
PizzaStore <|-- BeiJingPizzaStore

class DongJingPizzaStore{
    # createPizza(String type):Pizza
}

class NanJingPizzaStore{
    # createPizza(String type):Pizza
}

class BeiJingPizzaStore{
    # createPizza(String type):Pizza
}
@enduml